import React, { useState, useEffect } from "react";
import { StyleSheet } from "react-native";
import { Dropdown } from "react-native-element-dropdown";
import AntDesign from "@expo/vector-icons/AntDesign";

//ARTIST ONBOARDING LIST - SOLO OR GROUP
export const artistGroupSizeList = [
  "2",
  "3",
  "4",
  "5",
  "6",
  "7",
  "8",
  "9",
  "10+",
  //   "Violin",
  //   "Viola",
  //   "Cello",
  //   "Double Bass",
  //   "Guitar",
  //   "Harp",
  //   "Banjo",
  //   "Mandolin",
  //   "Ukulele",
  //   "Flute",
  //   "Clarinet",
  //   "Oboe",
  //   "Bassoon",
  //   "Saxophone",
  //   "Recorder",
  //   "Piccolo",
  //   "Trumpet",
  //   "Trombone",
  //   "French Horn",
  //   "Tuba",
  //   "Cornet",
  //   "Euphonium",
  //   "Drum Kit",
  //   "Snare Drum",
  //   "Bass Drum",
  //   "Cymbals",
  //   "Triangle",
  //   "Tambourine",
  //   "Marimba",
  //   "Xylophone",
  //   "Glockenspiel",
  //   "Timpani",
  //   "Bongo Drums",
  //   "Congas",
  //   "Piano",
  //   "Organ",
  //   "Harpsichord",
  //   "Accordion",
  //   "Synthesizer",
  //   "Electric Guitar",
  //   "Electric Bass",
  //   "Drum Machine",
  //   "Sampler",
  //   "Harmonica",
  //   "Bagpipes",
  //   "Theremin",
  //   "Sitar",
  //   "Didgeridoo",
];

//ARTIST ONBOARDING LIST - INSTRUMENT
export const instrumentsList = [
  "Violin",
  "Viola",
  "Cello",
  "Double Bass",
  "Guitar",
  "Harp",
  "Banjo",
  "Mandolin",
  "Ukulele",
  "Flute",
  "Clarinet",
  "Oboe",
  "Bassoon",
  "Saxophone",
  "Recorder",
  "Piccolo",
  "Trumpet",
  "Trombone",
  "French Horn",
  "Tuba",
  "Cornet",
  "Euphonium",
  "Drum Kit",
  "Snare Drum",
  "Bass Drum",
  "Cymbals",
  "Triangle",
  "Tambourine",
  "Marimba",
  "Xylophone",
  "Glockenspiel",
  "Timpani",
  "Bongo Drums",
  "Congas",
  "Piano",
  "Organ",
  "Harpsichord",
  "Accordion",
  "Synthesizer",
  "Electric Guitar",
  "Electric Bass",
  "Drum Machine",
  "Sampler",
  "Harmonica",
  "Bagpipes",
  "Theremin",
  "Sitar",
  "Didgeridoo",
].sort();

// export const instrumentsList = instruments.sort();

//ARTIST ONBOARDING LIST - MUSICAL GENRE
export const musicalGenresList = [
  "Pop",
  "Rock",
  "Hip-Hop",
  "Rap",
  "Country",
  "Classical",
  "Jazz",
  "Blues",
  "R&B (Rhythm and Blues)",
  "Soul",
  "Funk",
  "Electronic Dance Music (EDM)",
  "House",
  "Techno",
  "Dubstep",
  "Reggae",
  "Ska",
  "Punk",
  "Metal",
  "Alternative",
  "Indie",
  "Folk",
  "Gospel",
  "Latin",
  "Reggaeton",
  "K-Pop",
  "J-Pop",
  "World Music",
  "New Age",
  "Opera",
  "Disco",
  "Ambient",
  "Trance",
  "Grunge",
  "Swing",
  "Bluegrass",
  "Dancehall",
  "Salsa",
  "Merengue",
  "Bossa Nova",
].sort();

// export const musicalGenresList = musicalGenres.sort();

const artistTypesList = [];

const venueTypesList = [];

const styles = StyleSheet.create();
